on:
  push:
    branches: [master]
  workflow_dispatch:

name: deploy

jobs:

  render:
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    name: "Render and deploy CV"
    # Grant some permissions to allow deployment.
    permissions:
      pages: write
      id-token: write
    # Specify the deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      # Checkout the source
      - uses: actions/checkout@v4

      # Setup R, use binary packages for speedup (RStudio Package Manager)
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      # Install R package dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
      # Install pandoc (used to transform the markdown to HTML)
      - uses: r-lib/actions/setup-pandoc@v2
      # Install Chrome headless (used to print HTML to PDF)
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
      - run: pagedown::find_chrome()
        shell: Rscript {0}
#        env:
#          PAGEDOWN_CHROME: ${{ steps.setup-chrome.outputs.chrome-path }}
      # Install icons
      - run: icons::download_fontawesome(); icons::download_simple_icons()
        shell: Rscript {0}

      # Produce both "research" and "industry" CVs, in HTML and PDF versions
      - run: make OUT_DIR=docs all
#        env:
#          PAGEDOWN_CHROME: ${{ steps.setup-chrome.outputs.chrome-path }}

      # Upload the resulting "docs/" folder as an artifact so it can be later
      # used to deploy to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      # Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
